import { nanoid } from "@reduxjs/toolkit";
import { Image } from "react-native";

import { ValuableObject } from "../models/Inventory/slices";

export const assets = [
  require("../../assets/cartier_ring.png"),
  require("../../assets/lou_necklace.jpg"),
  require("../../assets/chanel_pearl.jpg"),
  require("../../assets/rolex_daytona.jpg"),
  require("../../assets/fake_bill.jpg"),
];

export const FAKE_DATA_INVENTORY: ValuableObject[] = [
  {
    id: nanoid(),
    rank: 1,
    category: "Jewelry",
    purchaseDate: new Date("11/25/1989").toISOString(),
    purchaseValue: "2500",
    mainImage: Image.resolveAssetSource(assets[0]).uri,
    name: "Cartier Ring",
    estimation: ["1800", "2300"],
    receipt: Image.resolveAssetSource(assets[4]).uri,
    contractId: "T_LUKO_HI_1",
  },
  {
    id: nanoid(),
    rank: 2,
    category: "Jewelry",
    purchaseDate: new Date("11/25/1989").toISOString(),
    purchaseValue: "2500",
    mainImage: Image.resolveAssetSource(assets[1]).uri,
    name: "Lou. Yetu Necklace",
    estimation: ["1800", "2300"],
    receipt: Image.resolveAssetSource(assets[4]).uri,
    contractId: "T_LUKO_HI_1",
  },
  {
    id: nanoid(),
    rank: 3,
    category: "Jewelry",
    purchaseDate: new Date("11/25/1989").toISOString(),
    purchaseValue: "2500",
    mainImage: Image.resolveAssetSource(assets[2]).uri,
    name: "Chanel Pearl Bracelet",
    estimation: ["1800", "2300"],
    receipt: Image.resolveAssetSource(assets[4]).uri,
    contractId: "T_LUKO_HI_1",
  },
  {
    id: nanoid(),
    rank: 4,
    category: "Jewelry",
    purchaseDate: new Date("11/25/1989").toISOString(),
    purchaseValue: "2500",
    mainImage: Image.resolveAssetSource(assets[3]).uri,
    name: "Rolex watch",
    estimation: ["1800", "2300"],
    receipt: Image.resolveAssetSource(assets[4]).uri,
    contractId: "T_LUKO_HI_1",
  },
  {
    id: nanoid(),
    rank: 5,
    category: "Jewelry",
    purchaseDate: new Date("11/25/1989").toISOString(),
    purchaseValue: "2500",
    mainImage: Image.resolveAssetSource(assets[0]).uri,
    name: "Cartier Ring #2",
    estimation: ["1800", "2300"],
    receipt: Image.resolveAssetSource(assets[4]).uri,
    contractId: "T_LUKO_HI_1",
  },
  {
    id: nanoid(),
    rank: 6,
    category: "Jewelry",
    purchaseDate: new Date("11/25/1989").toISOString(),
    purchaseValue: "2500",
    mainImage: Image.resolveAssetSource(assets[1]).uri,
    name: "Lou. Yetu Necklace #2",
    estimation: ["1800", "2300"],
    receipt: Image.resolveAssetSource(assets[4]).uri,
    contractId: "T_LUKO_HI_1",
  },
  {
    id: nanoid(),
    rank: 7,
    category: "Jewelry",
    purchaseDate: new Date("11/25/1989").toISOString(),
    purchaseValue: "2500",
    mainImage: Image.resolveAssetSource(assets[2]).uri,
    name: "Chanel Pearl Bracelet #2",
    estimation: ["1800", "2300"],
    receipt: Image.resolveAssetSource(assets[4]).uri,
    contractId: "T_LUKO_HI_1",
  },
  {
    id: nanoid(),
    rank: 8,
    category: "Jewelry",
    purchaseDate: new Date("11/25/1989").toISOString(),
    purchaseValue: "2500",
    mainImage: Image.resolveAssetSource(assets[3]).uri,
    name: "Rolex watch #2",
    estimation: ["1800", "2300"],
    receipt: Image.resolveAssetSource(assets[4]).uri,
    contractId: "T_LUKO_HI_1",
  },
];
