import { nanoid } from "@reduxjs/toolkit";

// import { assets } from "../screens/Inventory"
import { ValuableObject } from "../models/reducers/inventory";

export const assets = [
  require("../../assets/cartier_ring.png"),
  require("../../assets/lou_necklace.jpg"),
  require("../../assets/chanel_pearl.jpg"),
  require("../../assets/rolex_daytona.jpg"),
  require("../../assets/fake_bill.jpg"),
];

export const FAKE_DATA_INVENTORY: ValuableObject[] = [
  {
    id: nanoid(),
    rank: 1,
    category: "Jewelry",
    purchaseDate: new Date("11/25/1989").toISOString(),
    purchaseValue: "2500",
    mainImage: assets[0],
    name: "Cartier Ring",
    estimation: ["1800", "2300"],
    receipt: assets[4],
    contractId: "T_LUKO_HI_1",
  },
  {
    id: nanoid(),
    rank: 2,
    category: "Jewelry",
    purchaseDate: new Date("11/25/1989").toISOString(),
    purchaseValue: "2500",
    mainImage: assets[1],
    name: "Lou. Yetu Necklace",
    estimation: ["1800", "2300"],
    receipt: assets[4],
    contractId: "T_LUKO_HI_1",
  },
  {
    id: nanoid(),
    rank: 3,
    category: "Jewelry",
    purchaseDate: new Date("11/25/1989").toISOString(),
    purchaseValue: "2500",
    mainImage: assets[2],
    name: "Chanel Pearl Bracelet",
    estimation: ["1800", "2300"],
    receipt: assets[4],
    contractId: "T_LUKO_HI_1",
  },
  {
    id: nanoid(),
    rank: 4,
    category: "Jewelry",
    purchaseDate: new Date("11/25/1989").toISOString(),
    purchaseValue: "2500",
    mainImage: assets[3],
    name: "Rolex watch",
    estimation: ["1800", "2300"],
    receipt: assets[4],
    contractId: "T_LUKO_HI_1",
  },
  {
    id: nanoid(),
    rank: 5,
    category: "Jewelry",
    purchaseDate: new Date("11/25/1989").toISOString(),
    purchaseValue: "2500",
    mainImage: assets[0],
    name: "Cartier Ring #2",
    estimation: ["1800", "2300"],
    receipt: assets[4],
    contractId: "T_LUKO_HI_1",
  },
  {
    id: nanoid(),
    rank: 6,
    category: "Jewelry",
    purchaseDate: new Date("11/25/1989").toISOString(),
    purchaseValue: "2500",
    mainImage: assets[1],
    name: "Lou. Yetu Necklace #2",
    estimation: ["1800", "2300"],
    receipt: assets[4],
    contractId: "T_LUKO_HI_1",
  },
  {
    id: nanoid(),
    rank: 7,
    category: "Jewelry",
    purchaseDate: new Date("11/25/1989").toISOString(),
    purchaseValue: "2500",
    mainImage: assets[2],
    name: "Chanel Pearl Bracelet #2",
    estimation: ["1800", "2300"],
    receipt: assets[4],
    contractId: "T_LUKO_HI_1",
  },
  {
    id: nanoid(),
    rank: 8,
    category: "Jewelry",
    purchaseDate: new Date("11/25/1989").toISOString(),
    purchaseValue: "2500",
    mainImage: assets[3],
    name: "Rolex watch #2",
    estimation: ["1800", "2300"],
    receipt: assets[4],
    contractId: "T_LUKO_HI_1",
  },
];
